name: storagemarket
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ✅ Match Flutter's required intl version
  intl: ^0.20.2

  # ✅ Use version compatible with intl ^0.20.2
  form_builder_validators: ^11.2.0

  # Core Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9

  # State Management & Navigation
  get: ^4.6.6

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Image & Media
  image_picker: ^1.0.7
  photo_view: ^0.15.0

  # Utilities
  url_launcher: ^6.2.3
  share_plus: ^11.0.0
  path_provider: ^2.1.2
  connectivity_plus: ^6.1.4

  # Animations
  flutter_animate: ^4.3.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  intl_utils: ^2.8.4

flutter:
  uses-material-design: true
  generate: true
