// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkYXuoc17lyEdzqFmjNzMlyESnLgKf5v4',
    appId: '1:994031650684:web:318e44f1688e6120b9c6f9',
    messagingSenderId: '994031650684',
    projectId: 'storage-marketplace-f8fcc',
    authDomain: 'storage-marketplace-f8fcc.firebaseapp.com',
    storageBucket: 'storage-marketplace-f8fcc.firebasestorage.app',
    measurementId: 'G-SSBKSBNHFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPa4j1DYSwvmet0J-rFoQopInirFU0LS4',
    appId: '1:994031650684:android:233b52eb91d3123eb9c6f9',
    messagingSenderId: '994031650684',
    projectId: 'storage-marketplace-f8fcc',
    storageBucket: 'storage-marketplace-f8fcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_-eqvRSGuqjAkWcfzuhljj1b4yvErPk',
    appId: '1:994031650684:ios:779994a664a1d1d2b9c6f9',
    messagingSenderId: '994031650684',
    projectId: 'storage-marketplace-f8fcc',
    storageBucket: 'storage-marketplace-f8fcc.firebasestorage.app',
    iosBundleId: 'com.example.storageMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7_-eqvRSGuqjAkWcfzuhljj1b4yvErPk',
    appId: '1:994031650684:ios:779994a664a1d1d2b9c6f9',
    messagingSenderId: '994031650684',
    projectId: 'storage-marketplace-f8fcc',
    storageBucket: 'storage-marketplace-f8fcc.firebasestorage.app',
    iosBundleId: 'com.example.storageMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkYXuoc17lyEdzqFmjNzMlyESnLgKf5v4',
    appId: '1:994031650684:web:407caae1b3a41ca2b9c6f9',
    messagingSenderId: '994031650684',
    projectId: 'storage-marketplace-f8fcc',
    authDomain: 'storage-marketplace-f8fcc.firebaseapp.com',
    storageBucket: 'storage-marketplace-f8fcc.firebasestorage.app',
    measurementId: 'G-8X4S8SS79P',
  );
}
